apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: broker-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: broker.test
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitlab-broker-service
              port:
                number: 8000
